name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync

      - name: Test metadata generation
        run: |
          source .venv/bin/activate
          python generate_metadata.py
          test -f virtughan_qgis/metadata.txt

      - name: Test build
        run: ./build.sh

      - name: Verify plugin package
        run: |
          test -f dist/virtughan-qgis-plugin.zip
          unzip -t dist/virtughan-qgis-plugin.zip

      - name: Upload build artifact
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: plugin-package
          path: dist/virtughan-qgis-plugin.zip
